const dataHeader = [
  "ФИО/Дата",
  "28.04",
  "29.04",
  "30.04.",
  "31.04",
  "01.05",
  "02.05",
  "03.05",
  "04.05",
  "05.05",
  "06.05",
];

const dataStudents = [
  {
    id: 1,
    name: "Ivanov",
    group: "group_1",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 2,
    name: "Pvanov",
    group: "group_2",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 3,
    name: "Savanov",
    group: "group_3",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 4,
    name: "Matveienco",
    group: "group_1",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 5,
    name: "Putin",
    group: "group_2",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 6,
    name: "Lavrov",
    group: "group_3",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 7,
    name: "Utkin",
    group: "group_1",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 8,
    name: "Pituchov",
    group: "group_2",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
  {
    id: 9,
    name: "Medvediv",
    group: "group_3",
    object_1: ["1", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_2: ["2", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
    object_3: ["3", "v", "x", "v", "x", "v", "x", "v", "x", "v"],
  },
];
